# Generated by Django 3.2.12 on 2022-04-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChoiceField',
            new_name='Choice',
        ),
    ]
